### ISSUE TITLE
description error

### ISSUE THREAD

**Issue by ogry** [congatudo/stuff#9]
It seems to me that there is an error in

https://github.com/freeconga/stuff/blob/master/docs/install-valetudo.md#6-you-should-copy-now-the-new-valetudo-binary-file-generated-and-the-config-file-on-your-local-machine-to-a-rooted-conga

Where it says `<your pc ip>` it should put `<your conga ip>` since it is supposed to copy the file generated in the previous step to the Conga

**Comment by elraro** [comment]
Solved. Thanks.

https://github.com/congatudo/stuff/commit/6a63f8d5c4b2961660c3e9ce6a91990198daeb07
